<a href="https://colab.research.google.com/github/SammriddhGupta/watch-next/blob/main/movie_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting the dataset from Kaggle

In [1]:
from google.colab import files

In [ ]:
files.upload()

In [3]:
!pip install -q kaggle

In [4]:
!mkdir -p ~/.kaggle

In [5]:
!cp kaggle.json ~/.kaggle/

In [6]:
!chmod 600 ~/.kaggle/kaggle.json

In [7]:
!kaggle datasets download -d tmdb/tmdb-movie-metadata

 56% 5.00M/8.89M [00:00<00:00, 16.3MB/s]
100% 8.89M/8.89M [00:00<00:00, 25.6MB/s]


In [8]:
from zipfile import ZipFile
file_name = 'tmdb-movie-metadata.zip' #the file is your dataset exact name
with ZipFile(file_name, 'r') as zip:
  zip.extractall()
  print('Done')

Done


In [9]:
import numpy as np
import pandas as pd

In [10]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [11]:
movies.head()

budget  ... vote_count
0  237000000  ...      11800
1  300000000  ...       4500
2  245000000  ...       4466
3  250000000  ...       9106
4  260000000  ...       2124

[5 rows x 20 columns]

In [12]:
credits.head()

movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 4 columns]

In [13]:
movies.merge(credits,on='title')

budget  ...                                               crew
0     237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1     300000000  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     245000000  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     250000000  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     260000000  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...         ...  ...                                                ...
4804     220000  ...  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4805       9000  ...  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4806          0  ...  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4807          0  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4808          0  ...  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4809 rows x 23 columns]

In [14]:
movies.merge(credits,on='title').shape

(4809, 23)

In [15]:
movies.shape

(4803, 20)

In [16]:
credits.shape

(4803, 4)

In [17]:
movies = movies.merge(credits,on='title')

In [18]:
movies.shape

(4809, 23)

In [19]:
movies.head()

budget  ...                                               crew
0  237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1  300000000  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  245000000  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  250000000  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  260000000  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 23 columns]

# Preprocessing

## Analysis of all columns

budget - having a similar budget range will NOT help us recommend movies

genre - this will certainly help us 

homepage - NOT of use

id - will help us display movie posters

keywords - will provide us with tags 

orign lang - very skewed NOT of use

original title - we will NOT keep this, because the title column has all titles in english already, which is easier for us

overview - very important, helps us to find content similarity 

popularity - for our approach, will NOT help us

production_companies, production_countries - will NOT help us

release date - maybe some users might enjoy a certain 'era' of movies but the data is purely numerical so NOT of use

revenue - can be an indicator but again numerical so NOT of use

runtime - NOT of use

spoken_laguage, status - does NOT help 

tagline - is sometimes not related to the movie in order to sound cool, so NOT of use (instead we will use overview )

title - we will keep

vote_avg, vote_count - NOT of use

movie_id - we already have id so movie_id is NOT of use

cast, crew - relevant so we keep 


In [20]:
movies['original_language'].value_counts()

en    4510
fr      70
es      32
de      27
zh      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
fa       4
nl       4
th       3
he       3
cs       2
id       2
ta       2
ro       2
ar       2
nb       1
te       1
xx       1
hu       1
sl       1
tr       1
af       1
vi       1
ps       1
is       1
pl       1
el       1
ky       1
no       1
Name: original_language, dtype: int64

In [21]:
# we see that the data is very skewed, with a majority of movies in english, so we drop the original language column 

In [22]:
# Therefore, finally we will be keeping the following columns: 
# genres , movie_id , keywords, title , overview , cast and crew

In [23]:
movies = movies[['movie_id' , 'title' , 'overview' , 'genres' , 'keywords' , 'cast' , 'crew']]

In [24]:
movies.head()

movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

## Goal from here on out

#### We want to generate a column called tags for our use so we will merge all columns except movie_id and title

we need to convert the data in a useful format

we'll use the top 3 actors from the cast and only the director from the crew

so we will get a paragraph for every movie

In [25]:
# checking for missing data 

movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [26]:
# we drop those rows from overview which are null
movies.dropna(inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [27]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [28]:
# now checking for duplicate data
movies.duplicated().sum()

0

In [29]:
# we have no duplicates yay

movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [30]:
# right now we have a list of dictionaries, we need to get into a format like ['Action' , 'Adventure' , 'Fantasy' , 'Science Fiction' ]
# we can see the list is made up of strings

# let's define a helper function to do so
def convert(obj):
  L = []
  for i in obj:
    L.append(i['name'])
  return L

In [31]:
# the below code has been commented because it gives an error

#convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')


In [32]:
# as we can see we are getting the error string indices must be integers
# we need to convert the string of lists into a list
# we use a python module called 'ast' for this

import ast 
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [33]:
# Look, our problem is solved 
def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [34]:
 movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [35]:
# now we get a list of all genres for every movie EXACTLY WHAT WE WANTED MUAHAHAHA
movies['genres'] =  movies['genres'].apply(convert)

In [36]:
movies.head()

movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [37]:
# doing the same for the keywords column
movies['keywords'].apply(convert)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...                        
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [38]:
movies['keywords'] = movies['keywords'].apply(convert)

In [39]:
movies.head()

movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [40]:
# for the cast we need the names of the first 3 actors so we need to extract the first 3 dictionaries
def convert3(obj):
  L = []
  counter=0
  for i in ast.literal_eval(obj):
    if counter!=3:
      L.append(i['name'])
      counter+=1                    # just note- counter++ does not work in python lol 
    else:
      break
  return L

In [41]:
movies['cast'].apply(convert3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...                        
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [42]:
movies['cast'] = movies['cast'].apply(convert3)

In [43]:
movies.head()

movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [44]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"},

In [45]:
# we need to extract from the crew, the names with the department director
# let's make a helper function for that

def fetch_director(obj):
  L = []
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      L.append(i['name'])
      break                  
  return L

In [46]:
movies['crew'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...         
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [47]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [48]:
movies.head()

movie_id  ...                 crew
0     19995  ...      [James Cameron]
1       285  ...     [Gore Verbinski]
2    206647  ...         [Sam Mendes]
3     49026  ...  [Christopher Nolan]
4     49529  ...     [Andrew Stanton]

[5 rows x 7 columns]

In [49]:
# 🔥🔥🔥

In [50]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [51]:
# let's convert this list to a string 
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...                        
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [52]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [53]:
movies.head()

movie_id  ...                 crew
0     19995  ...      [James Cameron]
1       285  ...     [Gore Verbinski]
2    206647  ...         [Sam Mendes]
3     49026  ...  [Christopher Nolan]
4     49529  ...     [Andrew Stanton]

[5 rows x 7 columns]

In [54]:
# now we need to apply a little transformation to our genres, keywords, cast and crew columns to remove the spaces between words in them
# Why? Notice that the cast has a 'Sam Worthington' and the crew has a director 'Sam Mendes' 
# if we leave the columns as it is, while making our tags, our recommender system will get confused which 'Sam' are we referring to
# therfore we shall remove the space between all words and make them ScienceFiction , cultureclash, SamWorthington , SamMendes and so on

movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...                     
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [55]:
# applying this to all four of our columns

movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [56]:
movies.head()

movie_id  ...                crew
0     19995  ...      [JamesCameron]
1       285  ...     [GoreVerbinski]
2    206647  ...         [SamMendes]
3     49026  ...  [ChristopherNolan]
4     49529  ...     [AndrewStanton]

[5 rows x 7 columns]

In [57]:
# WOOHOO WE HAVE OUR PROCESSED DATA 🔥🔥🔥🔥

In [58]:
# now we convert our data into a new column tags

In [59]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew'] 

In [60]:
movies.head()

movie_id  ...                                               tags
0     19995  ...  [In, the, 22nd, century,, a, paraplegic, Marin...
1       285  ...  [Captain, Barbossa,, long, believed, to, be, d...
2    206647  ...  [A, cryptic, message, from, Bond’s, past, send...
3     49026  ...  [Following, the, death, of, District, Attorney...
4     49529  ...  [John, Carter, is, a, war-weary,, former, mili...

[5 rows x 8 columns]

In [61]:
new_df = movies[['movie_id', 'title' , 'tags']]

In [62]:
new_df

movie_id  ...                                               tags
0        19995  ...  [In, the, 22nd, century,, a, paraplegic, Marin...
1          285  ...  [Captain, Barbossa,, long, believed, to, be, d...
2       206647  ...  [A, cryptic, message, from, Bond’s, past, send...
3        49026  ...  [Following, the, death, of, District, Attorney...
4        49529  ...  [John, Carter, is, a, war-weary,, former, mili...
...        ...  ...                                                ...
4804      9367  ...  [El, Mariachi, just, wants, to, play, his, gui...
4805     72766  ...  [A, newlywed, couple's, honeymoon, is, upended...
4806    231617  ...  ["Signed,, Sealed,, Delivered", introduces, a,...
4807    126186  ...  [When, ambitious, New, York, attorney, Sam, is...
4808     25975  ...  [Ever, since, the, second, grade, when, he, fi...

[4806 rows x 3 columns]

In [63]:
 new_df['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [64]:
# for convenience let's convert all the text to lowercase
new_df['tags'] = new_df['tags'].apply(lambda x:str(x).lower())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [65]:
new_df

movie_id  ...                                               tags
0        19995  ...  ['in', 'the', '22nd', 'century,', 'a', 'parapl...
1          285  ...  ['captain', 'barbossa,', 'long', 'believed', '...
2       206647  ...  ['a', 'cryptic', 'message', 'from', 'bond’s', ...
3        49026  ...  ['following', 'the', 'death', 'of', 'district'...
4        49529  ...  ['john', 'carter', 'is', 'a', 'war-weary,', 'f...
...        ...  ...                                                ...
4804      9367  ...  ['el', 'mariachi', 'just', 'wants', 'to', 'pla...
4805     72766  ...  ['a', 'newlywed', "couple's", 'honeymoon', 'is...
4806    231617  ...  ['"signed,', 'sealed,', 'delivered"', 'introdu...
4807    126186  ...  ['when', 'ambitious', 'new', 'york', 'attorney...
4808     25975  ...  ['ever', 'since', 'the', 'second', 'grade', 'w...

[4806 rows x 3 columns]

# Text Vectorization

### We will use the bag of words technique to vectorize the text

first concatenate all the tags to make a gigantic string/large text
then we find the most common words in that large text, in our case the 5000 most common words 

again taking the tags for each movie, we check how many times each tag has occured, and form a dataframe/table of shape (5000,5000) 

now every movie is a vector in a 5000 dimensional space

note: we will not consider stop-words like 'are' 'and' 'or' 'to' 'from' while performing vectorization

In [66]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [67]:
cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [68]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [69]:
vectors = cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [70]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [71]:
cv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'ad

In [72]:
# we notice in the above output that words like actor actors, activity activities , action actions are being counted as separate words
# we apply stemming 

In [73]:
pd.options.mode.chained_assignment = None  # default='warn'

In [74]:
import nltk

In [75]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [76]:
def stem(text):
  y=[]
  for i in text.split():
    ps.stem(i)

In [77]:
# demonstrating the stem function
ps.stem('dancing')

'danc'

In [78]:
def stem(text):
  y=[ ]

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y) 

In [79]:
new_df['tags'].apply(stem)[0]

"['in', 'the', '22nd', 'century,', 'a', 'paraplegic', 'marine', 'is', 'dispatched', 'to', 'the', 'moon', 'pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn', 'between', 'following', 'orders', 'and', 'protecting', 'an', 'alien', 'civilization.', 'action', 'adventure', 'fantasy', 'sciencefiction', 'cultureclash', 'future', 'spacewar', 'spacecolony', 'society', 'spacetravel', 'futuristic', 'romance', 'space', 'alien', 'tribe', 'alienplanet', 'cgi', 'marine', 'soldier', 'battle', 'loveaffair', 'antiwar', 'powerrelations', 'mindandsoul', '3d', 'samworthington', 'zoesaldana', 'sigourneyweaver', 'jamescameron']"

In [80]:
new_df['tags'] = new_df['tags'].apply(stem)

In [81]:
new_df.head()

movie_id  ...                                               tags
0     19995  ...  ['in', 'the', '22nd', 'century,', 'a', 'parapl...
1       285  ...  ['captain', 'barbossa,', 'long', 'believed', '...
2    206647  ...  ['a', 'cryptic', 'message', 'from', 'bond’s', ...
3     49026  ...  ['following', 'the', 'death', 'of', 'district'...
4     49529  ...  ['john', 'carter', 'is', 'a', 'war-weary,', 'f...

[5 rows x 3 columns]

In [82]:
new_df['tags'][0]

"['in', 'the', '22nd', 'century,', 'a', 'paraplegic', 'marine', 'is', 'dispatched', 'to', 'the', 'moon', 'pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn', 'between', 'following', 'orders', 'and', 'protecting', 'an', 'alien', 'civilization.', 'action', 'adventure', 'fantasy', 'sciencefiction', 'cultureclash', 'future', 'spacewar', 'spacecolony', 'society', 'spacetravel', 'futuristic', 'romance', 'space', 'alien', 'tribe', 'alienplanet', 'cgi', 'marine', 'soldier', 'battle', 'loveaffair', 'antiwar', 'powerrelations', 'mindandsoul', '3d', 'samworthington', 'zoesaldana', 'sigourneyweaver', 'jamescameron']"

In [83]:
# now we repeat the vectorizing steps again

In [84]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [85]:
vectors = cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [86]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [87]:
cv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'ad

# We'll calculate cosine angle

In [88]:
from sklearn.metrics.pairwise import cosine_similarity

In [89]:
cosine_similarity(vectors)

array([[1.        , 0.09107651, 0.05976143, ..., 0.02548236, 0.02817181,
        0.        ],
       [0.09107651, 1.        , 0.06350006, ..., 0.02707652, 0.        ,
        0.        ],
       [0.05976143, 0.06350006, 1.        , ..., 0.02665009, 0.        ,
        0.        ],
       ...,
       [0.02548236, 0.02707652, 0.02665009, ..., 1.        , 0.07537784,
        0.04828045],
       [0.02817181, 0.        , 0.        , ..., 0.07537784, 1.        ,
        0.05337605],
       [0.        , 0.        , 0.        , ..., 0.04828045, 0.05337605,
        1.        ]])

In [90]:
cosine_similarity(vectors).shape

(4806, 4806)

In [91]:
similarity = cosine_similarity(vectors)

In [92]:
similarity.shape

(4806, 4806)

In [93]:
similarity[0]

array([1.        , 0.09107651, 0.05976143, ..., 0.02548236, 0.02817181,
       0.        ])

In [94]:
# this is showing the similarity scores of the movie 1 with allllllll the other movies
similarity[1]

array([0.09107651, 1.        , 0.06350006, ..., 0.02707652, 0.        ,
       0.        ])

In [95]:
# now we might think that simply sorting the distances in the function below will help us 
# find the top 5 movies most similar to the entered movie but the problem is sorting will change their index
# then we can no longer find out which index number is it i.w which movie is this which is most similar
# so we use enumerate function

In [96]:
sorted(list(enumerate(similarity[0])),reverse=True, key = lambda x:x[1])

[(0, 1.0),
 (539, 0.26089696604360174),
 (1194, 0.2581988897471611),
 (507, 0.2507132682112035),
 (1216, 0.24944382578492943),
 (260, 0.24688535993934702),
 (582, 0.24397501823713333),
 (1920, 0.243599382882345),
 (3730, 0.23904572186687872),
 (1444, 0.2344036154692477),
 (74, 0.22934123614693147),
 (322, 0.2253744679276044),
 (3608, 0.2238868314198225),
 (83, 0.22190115272469205),
 (61, 0.22131333406899523),
 (4192, 0.22131333406899523),
 (1537, 0.21971768720102053),
 (2333, 0.2173253797873328),
 (1204, 0.21653278478430665),
 (47, 0.2164218276749025),
 (495, 0.2162249910469341),
 (972, 0.21602468994692864),
 (2409, 0.2138089935299395),
 (942, 0.21251185925162067),
 (466, 0.2114722130550724),
 (1329, 0.21147221305507238),
 (2971, 0.21096325392232296),
 (2204, 0.2059714602177749),
 (151, 0.20498001542269692),
 (973, 0.20291986247835692),
 (1201, 0.20283702113484398),
 (1275, 0.19889806323953876),
 (2999, 0.19518001458970666),
 (4405, 0.19518001458970666),
 (2786, 0.19518001458970663),
 

In [97]:
sorted(list(enumerate(similarity[0])),reverse=True, key = lambda x:x[1])[1:6]

[(539, 0.26089696604360174),
 (1194, 0.2581988897471611),
 (507, 0.2507132682112035),
 (1216, 0.24944382578492943),
 (260, 0.24688535993934702)]

In [98]:
# making a function to recommend movies
def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True, key = lambda x:x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

In [99]:
recommend('Iron Man')

Iron Man 2
Iron Man 3
Avengers: Age of Ultron
Captain America: Civil War
The Avengers


In [100]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman & Robin
Batman


In [101]:
recommend('Annabelle')

Real Women Have Curves
Lovely & Amazing
Jesus' Son
The Shipping News
The Inkwell


In [102]:
recommend('White House Down')

Olympus Has Fallen
Absolute Power
In Her Line of Fire
G.I. Joe: Retaliation
My Fellow Americans


In [103]:
recommend('Titanic')

Captain Phillips
The Notebook
Ghost Ship
In the Heart of the Sea
Poseidon


In [104]:
# YAY our model is readyyyyy 

In [105]:
import pickle 

In [106]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [107]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [108]:
pickle.dump(similarity,open('similarity.pkl','wb'))